# Generated by Django 3.1.2 on 2020-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Blog', 'Blog'), ('Photography', 'Photography'), ('Culture', 'Culture'), ('Tv', 'Tv'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Life', 'Life'), ('God', 'God'), ('Movies', 'Movies'), ('Culture', 'Culture'), ('Weather', 'Weather'), ('Art', 'Art'), ('Space', 'Space'), ('Nature', 'Nature'), ('Computer', 'Computer'), ('SocialMedia', 'SocialMedia')], default='AddCategory', max_length=255),
        ),
    ]
