# Generated by Django 3.1.2 on 2020-11-30 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201130_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 17, 12, 52, 82074, tzinfo=utc)),
        ),
    ]
