# Generated by Django 3.1.2 on 2020-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201125_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[], default='AddCategory', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='AddTags', max_length=255),
        ),
    ]
