# Generated by Django 3.1.2 on 2020-12-01 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201201_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 12, 23, 18, 741490, tzinfo=utc)),
        ),
    ]
