# Generated by Django 3.1.2 on 2020-12-01 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20201202_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 19, 1, 37, 738260, tzinfo=utc)),
        ),
    ]
