# Generated by Django 3.1.2 on 2020-12-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20201202_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='upload_pics'),
        ),
    ]
