# Generated by Django 3.1.2 on 2020-12-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20201202_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Culture', 'Culture'), ('Entertainment & Pop Culture', 'Entertainment & Pop Culture'), ('Fashion', 'Fashion'), ('Geography & Travel', 'Geography & Travel'), ('Health & Medicine', 'Health & Medicine'), ('Literature', 'Literature'), ('Lifestyle', 'Lifestyle'), ('Movies', 'Movies'), ('Nature', 'Nature'), ('Photography', 'Photography'), ('Philosophy & Religion', 'Philosophy & Religion'), ('Politics, Law & Government', 'Politics, Law & Government'), ('Science', 'Science'), ('Social Issues', 'Social Issues'), ('Space', 'Space'), ('Sports & Recreation', 'Sports & Recreation'), ('Technology', 'Technology'), ('Visual Arts', 'Visual Arts'), ('World History', 'World History')], default='AddCategory', max_length=255),
        ),
    ]
