# Generated by Django 3.1.2 on 2020-12-03 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0013_auto_20201202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_postss', to=settings.AUTH_USER_MODEL),
        ),
    ]
